version: '3.8'

volumes:
  dbdata:

services:
  web:
    image: laravelapp:latest
    build:
      context: .
      dockerfile: Dockerfile.fpm
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    depends_on:
      - db


  db:
    # platform: "linux/arm64"
    image: mysql:latest
    env_file:
      - .env 
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3006:3006"
    volumes:
      - dbdata:/var/lib/mysql